import { z } from 'zod';

const DamageTypeSchema = z.enum([
  'acid',
  'bludgeoning',
  'cold',
  'fire',
  'force',
  'lightning',
  'necrotic',
  'piercing',
  'poison',
  'psychic',
  'radiant',
  'slashing',
  'thunder',
]);

export const DescriptiveActionSchema = z.object({
  name: z.string(),
  action_type: z.literal('descriptive'),
  desc: z.string(),
});

export const MeleeWeaponAttackSchema = z.object({
  name: z.string(),
  action_type: z.literal('melee weapon attack'),
  desc: z.string().optional(),
  additional_damage_dice: z.string().optional(),
  additional_damage_type: DamageTypeSchema.optional(),
  additional_default_damage: z.number().int().positive().optional(),
  attack_bonus: z.number(),
  damage_bonus: z.number(),
  damage_dice: z.string(),
  damage_type: DamageTypeSchema,
  default_damage: z.number(),
  reach: z.string(),
});

export const RangedWeaponAttackSchema = z.object({
  name: z.string(),
  action_type: z.literal('ranged weapon attack'),
  desc: z.string().optional(),
  attack_bonus: z.number(),
  damage_bonus: z.number(),
  damage_dice: z.string(),
  damage_type: DamageTypeSchema,
  default_damage: z.number(),
  range: z.string(),
});

export const SkillsSchema = z.object({
  acrobatics: z.number().int().positive().optional(),
  animal_handling: z.number().int().positive().optional(),
  arcana: z.number().int().positive().optional(),
  athletics: z.number().int().positive().optional(),
  deception: z.number().int().positive().optional(),
  history: z.number().int().positive().optional(),
  insight: z.number().int().positive().optional(),
  intimidation: z.number().int().positive().optional(),
  investigation: z.number().int().positive().optional(),
  medicine: z.number().int().positive().optional(),
  nature: z.number().int().positive().optional(),
  perception: z.number().int().positive().optional(),
  performance: z.number().int().positive().optional(),
  persuasion: z.number().int().positive().optional(),
  religion: z.number().int().positive().optional(),
  sleight_of_hand: z.number().int().positive().optional(),
  stealth: z.number().int().positive().optional(),
  survival: z.number().int().positive().optional(),
});

const ActionSchema = z.union([
  DescriptiveActionSchema,
  MeleeWeaponAttackSchema,
  RangedWeaponAttackSchema,
]);

export const StatBlockSchema = z.object({
  id: z.string(),
  desc: z.string().optional(),
  name: z.string(),
  size: z.enum([
    'tiny',
    'small',
    'medium',
    'large',
    'huge',
    'gargantuan',
  ]),
  type: z.enum([
    'aberration',
    'beast',
    'celestial',
    'construct',
    'dragon',
    'elemental',
    'fey',
    'fiend',
    'giant',
    'humanoid',
    'monstrosity',
    'ooze',
    'plant',
    'undead',
  ]),
  subtype: z.string().optional(),
  group: z.string().nullable().optional(),
  alignment: z.enum([
    'any',
    'unaligned',
    'any non-lawful alignment',
    'lawful good',
    'neutral good',
    'chaotic good',
    'lawful neutral',
    'neutral',
    'chaotic neutral',
    'lawful evil',
    'neutral evil',
    'chaotic evil',
  ]),
  armor_class: z.number(),
  armor_desc: z.string().nullable().optional(),
  hit_points: z.number(),
  hit_dice: z.string(),
  speed: z.object({
    climb: z.number().optional(),
    fly: z.number().optional(),
    swim: z.number().optional(),
    walk: z.number().optional(),
  }),
  strength: z.number(),
  dexterity: z.number(),
  constitution: z.number(),
  intelligence: z.number(),
  wisdom: z.number(),
  charisma: z.number(),
  strength_save: z.number().nullable().optional(),
  dexterity_save: z.number().nullable().optional(),
  constitution_save: z.number().nullable().optional(),
  intelligence_save: z.number().nullable().optional(),
  wisdom_save: z.number().nullable().optional(),
  charisma_save: z.number().nullable().optional(),
  perception: z.number().nullable().optional(),
  skills: SkillsSchema.optional(),
  proficiency_bonus: z.number().int().positive(),
  damage_vulnerabilities: z.string().optional(),
  damage_resistances: z.string().optional(),
  damage_immunities: z.string().optional(),
  condition_immunities: z.string().optional(),
  senses: z.string(),
  languages: z.string(),
  challenge_rating: z.string(),
  cr: z.number(),
  actions: z.array(ActionSchema),
  bonus_actions: z.array(z.string()).nullable().optional(),
  reactions: z.array(z.object({
    name: z.string(),
    desc: z.string(),
  })).nullable().optional(),
  legendary_desc: z.string().optional(),
  legendary_actions: z.array(z.string()).nullable().optional(),
  special_abilities: z.array(z.object({
    name: z.string(),
    desc: z.string(),
  })).nullable(),
  spell_list: z.array(z.string()),
  page_no: z.number(),
  environments: z.array(z.enum([
    'arctic',
    'coastal',
    'desert',
    'forest',
    'grassland',
    'hill',
    'mountain',
    'swamp',
    'underdark',
    'underwater',
    'urban',
  ])),
  img_main: z.string().nullable().optional(),
  document__slug: z.string(),
  document__title: z.string(),
  document__license_url: z.string(),
  document__url: z.string(),
  v2_converted_path: z.string(),
});
