import { z } from 'zod';

export const StatBlockSchema = z.object({
  id: z.string(),
  desc: z.string().optional(),
  name: z.string(),
  size: z.enum([
    'tiny',
    'small',
    'medium',
    'large',
    'huge',
    'gargantuan',
  ]),
  type: z.enum([
    'aberration',
    'beast',
    'celestial',
    'construct',
    'dragon',
    'elemental',
    'fey',
    'fiend',
    'giant',
    'humanoid',
    'monstrosity',
    'ooze',
    'plant',
    'undead',
  ]),
  subtype: z.string().optional(),
  group: z.string().nullable().optional(),
  alignment: z.enum([
    'lawful good',
    'neutral good',
    'chaotic good',
    'lawful neutral',
    'neutral',
    'chaotic neutral',
    'lawful evil',
    'neutral evil',
    'chaotic evil',
  ]),
  armor_class: z.number(),
  armor_desc: z.string().nullable().optional(),
  hit_points: z.number(),
  hit_dice: z.string(),
  speed: z.object({
    fly: z.number().optional(),
    swim: z.number().optional(),
    walk: z.number().optional(),
  }),
  strength: z.number(),
  dexterity: z.number(),
  constitution: z.number(),
  intelligence: z.number(),
  wisdom: z.number(),
  charisma: z.number(),
  strength_save: z.number().nullable().optional(),
  dexterity_save: z.number().nullable().optional(),
  constitution_save: z.number().nullable().optional(),
  intelligence_save: z.number().nullable().optional(),
  wisdom_save: z.number().nullable().optional(),
  charisma_save: z.number().nullable().optional(),
  perception: z.number().nullable().optional(),
  skills: z.record(z.string(), z.string()).optional(),
  proficiency_bonus: z.string(),
  damage_vulnerabilities: z.string().optional(),
  damage_resistances: z.string().optional(),
  damage_immunities: z.string().optional(),
  condition_immunities: z.string().optional(),
  senses: z.string(),
  languages: z.string(),
  challenge_rating: z.string(),
  cr: z.number(),
  actions: z.array(z.object({
    name: z.string(),
    type: z.enum([
      'melee weapon attack',
      'ranged weapon attack',
    ]),
    desc: z.string().optional(),
    attack_bonus: z.number(),
    damage_type: z.enum([
      'acid',
      'bludgeoning',
      'cold',
      'fire',
      'force',
      'lightning',
      'necrotic',
      'piercing',
      'poison',
      'psychic',
      'radiant',
      'slashing',
      'thunder',
    ]),
    damage_dice: z.string(),
    damage_bonus: z.number(),
    default_damage: z.number(),
    range: z.string().optional(),
    reach: z.string().optional(),
  })),
  bonus_actions: z.array(z.string()).nullable().optional(),
  reactions: z.array(z.string()).nullable().optional(),
  legendary_desc: z.string().optional(),
  legendary_actions: z.array(z.string()).nullable().optional(),
  special_abilities: z.array(z.object({
    name: z.string(),
    desc: z.string(),
  })),
  spell_list: z.array(z.string()),
  page_no: z.number(),
  environments: z.array(z.enum([
    'arctic',
    'coastal',
    'desert',
    'forest',
    'grassland',
    'hill',
    'mountain',
    'swamp',
    'underdark',
    'underwater',
    'urban',
  ])),
  img_main: z.string().nullable().optional(),
  document__slug: z.string(),
  document__title: z.string(),
  document__license_url: z.string(),
  document__url: z.string(),
  v2_converted_path: z.string(),
});
